# Specify a base image
FROM node:alpine

WORKDIR /app

# Copy external files needed by container
COPY ./package.json .

# Install some dependencies
RUN npm install
COPY . .

# Default command
CMD ["npm","run","start"]