sudo: required
services: 
  - docker

before_install:
  - docker build -t maeri/frontend -f ./frontend/Dockerfile.dev ./frontend/. 

script:
  - docker run -e CI=true maeri/frontend npm run test -- --coverage
